---
Rakefile:
  extras:
    - 'PuppetSyntax.exclude_paths = ["plans/**/*.pp", "vendor/**/*"]'
Gemfile:
  optional:
    ':development':
      - gem: 'generate-puppetfile'
        version: '~> 1.0'
.gitignore:
  paths:
#local env item
    - '.ruby-version'
