---
Rakefile:
  extras:
    - 'PuppetSyntax.exclude_paths = ["plans/**/*.pp", "vendor/**/*"]'
Gemfile:
  optional:
    ':development':
      - gem: 'puppetfile-updater'
        version: '~> 0.5.0'
      - gem: 'generate-puppetfile'
        version: '~> 1.0'
